### ISSUE TITLE
Screna throwing unhandled NullReferenceException exception in OnStop

### ISSUE THREAD

**Issue by MichielDean** [MathewSachin/Screna#11]
I am using Screna to write screenshots of our selenium tests to a video.
When I stop the video, Screna.Recorder.OnStop() is throwing a NullReferenceException.

Here is the stack trace:
Application: QTAgent32_40.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Screna.Recorder.OnStop()
   at Screna.RecorderBase.Stop()
   at Screna.Recorder.Record()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

I tired making some changes to the recorder class, but have been unsuccessful so far.

**Comment by MathewSachin** [comment]
Try using the Recorder on a separate thread.

**Comment by MichielDean** [comment]
I tried starting the recorder in a new thread and it did not solve the issue.
To start the recorder:
`_recorder = new SeleniumVideoRecorder(this, _isGridNode, true);`
`_recorderThread = new Thread(_recorder.StartVideoCapture);`
`_recorderThread.Start();`

Then to stop:
`_recorder.StopVideoCapture();`
`_recorderThread.Join();`

It looks like Screna is also throwing an ObjectDisposedException as well:
Exception Info: System.ObjectDisposedException
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean ByRef)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(System.Runtime.InteropServices.SafeHandle, Boolean ByRef)
   at Microsoft.Win32.Win32Native.SetEvent(Microsoft.Win32.SafeHandles.SafeWaitHandle)
   at System.Threading.EventWaitHandle.Set()
   at Screna.Recorder.OnStop()
   at Screna.RecorderBase.Stop()
   at Screna.Recorder.Record()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by MichielDean** [comment]
Hey Matthew,
Let me know if there is anything I can do to help with this.

**Comment by MathewSachin** [comment]
Ok. Tell me which objects are null are which exact object is throwing ObjectDisposedException. Please tell me the exact variable names because I was not able to reciprocate the issue.

**Comment by MichielDean** [comment]
Looks like the object disposed exception is being thrown in the Recorder OnStop method:
// Resume if Paused
_continueCapturing?.Set();

I was able to reproduce it very reliably by putting locks around the entire OnStop method and inside the top while loop of the Record method.

**Comment by MichielDean** [comment]
The object reference issue is much harder to track down. It might be safer to implement IDisposable on the recorder itself and move many of the dispose calls to that,

**Comment by MathewSachin** [comment]
Please test with v0.8.0.
It works fine on my side.
